import { jsPDF } from "jspdf";
import "jspdf-autotable";

export interface ClassReport {
  schoolName: string;
  className: string;
  dateGenerated: string;
  summary: {
    totalStudents: number;
    avgMarks: number;
    passPercentage: number;
    attendanceRate: number;
    avgOaaScore: number | null;
    classPotential: number | null;
  };
  subjects: {
    subject: string;
    avg: number;
    highest: number;
    lowest: number;
    passPercentage: number;
  }[];
  topPerformers: {
    rank: number;
    name: string;
    avgMarks: number;
    grade: string;
    oaaScore: number | null;
  }[];
  atRiskStudents: {
    name: string;
    avgMarks: number;
    attendance: number;
    riskScore: number;
    redDotCount: number;
  }[];
}

export function generateClassPDF(data: ClassReport): void {
  const doc = new jsPDF();
  const primaryColor = [79, 70, 229]; // #4F46E5 (Indigo)
  const darkSlate = [30, 41, 59]; // #1E293B (Slate-800)
  const lightSlate = [100, 116, 139]; // #64748B (Slate-500)
  const borderSlate = [226, 232, 240]; // Slate-200

  // Page Setup & EduTrack branding
  const drawPageDecorations = (pageNum: number) => {
    // Top border accent
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, 210, 4, "F");

    // Header branding
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text("OAA.ai", 15, 12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
    doc.text("Performance Analytics Platform", 29, 12);

    // Footer
    doc.setFontSize(8);
    doc.text(`Generated by OAA.ai Class Analytics  |  Page ${pageNum}`, 15, 287);
    doc.text(data.dateGenerated, 165, 287);
  };

  drawPageDecorations(1);

  // Document Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.text("Class Performance Summary Report", 15, 28);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
  doc.text(`School: ${data.schoolName}`, 15, 34);
  doc.text(`Class: Class ${data.className}`, 15, 39);
  doc.text(`Generated On: ${data.dateGenerated}`, 15, 44);

  // Section 1: Summary stats cards (3x2 grid)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.text("Key Analytics Metrics", 15, 54);

  // Row 1: Left Card (Class size)
  doc.setFillColor(248, 250, 252); // bg-slate-50
  doc.rect(15, 58, 56, 18, "F");
  doc.setDrawColor(borderSlate[0], borderSlate[1], borderSlate[2]);
  doc.rect(15, 58, 56, 18, "S");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
  doc.text("CLASS SIZE", 19, 64);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text(String(data.summary.totalStudents), 19, 72);

  // Row 1: Middle Card (Average Marks)
  doc.setFillColor(248, 250, 252);
  doc.rect(77, 58, 56, 18, "F");
  doc.rect(77, 58, 56, 18, "S");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
  doc.text("MARKS AVERAGE", 81, 64);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text(`${data.summary.avgMarks.toFixed(1)}%`, 81, 72);

  // Row 1: Right Card (Class Potential)
  const cpValue = data.summary.classPotential !== null ? data.summary.classPotential : 0;
  doc.setFillColor(248, 250, 252);
  doc.rect(139, 58, 56, 18, "F");
  doc.rect(139, 58, 56, 18, "S");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
  doc.text("CLASS POTENTIAL (CP)", 143, 64);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text(`${cpValue.toFixed(1)}%`, 143, 72);

  // Row 2: Left Card (Average OAA Score)
  const avgOaa = data.summary.avgOaaScore !== null ? data.summary.avgOaaScore : 0;
  doc.setFillColor(248, 250, 252);
  doc.rect(15, 80, 56, 18, "F");
  doc.rect(15, 80, 56, 18, "S");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
  doc.text("AVERAGE OAA SCORE", 19, 86);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text(avgOaa.toFixed(1), 19, 94);

  // Row 2: Middle Card (Pass Rate)
  doc.setFillColor(248, 250, 252);
  doc.rect(77, 80, 56, 18, "F");
  doc.rect(77, 80, 56, 18, "S");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
  doc.text("PASS RATE (>=40%)", 81, 86);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text(`${data.summary.passPercentage.toFixed(1)}%`, 81, 94);

  // Row 2: Right Card (Average Attendance)
  doc.setFillColor(248, 250, 252);
  doc.rect(139, 80, 56, 18, "F");
  doc.rect(139, 80, 56, 18, "S");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
  doc.text("AVERAGE ATTENDANCE", 143, 86);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text(`${data.summary.attendanceRate.toFixed(1)}%`, 143, 94);

  // Section 2: Subject-wise performance table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.text("Subject-wise Performance Analysis", 15, 111);

  const subjectRows = data.subjects.map((s) => [
    s.subject,
    `${s.avg.toFixed(1)}%`,
    `${s.highest.toFixed(1)}%`,
    `${s.lowest.toFixed(1)}%`,
    `${s.passPercentage.toFixed(1)}%`,
  ]);

  type DocWithAutoTable = jsPDF & { 
    autoTable: (opt: object) => void;
    lastAutoTable: { finalY: number };
  };

  (doc as unknown as DocWithAutoTable).autoTable({
    startY: 115,
    head: [["Subject Title", "Class Average", "Highest Score", "Lowest Score", "Pass Rate"]],
    body: subjectRows,
    theme: "striped",
    headStyles: { fillColor: primaryColor, fontStyle: "bold", fontSize: 8.5 },
    bodyStyles: { textColor: darkSlate, fontSize: 8 },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: 15, right: 15 },
  });

  // Section 3: Top Performers Table
  const finalY1 = (doc as unknown as DocWithAutoTable).lastAutoTable.finalY;
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.text("Top Performers (Ranked by Composite OAA Score)", 15, finalY1 + 10);

  const topRows = data.topPerformers.map((p) => [
    `#${p.rank}`,
    p.name,
    `${p.avgMarks.toFixed(1)}%`,
    p.grade,
    p.oaaScore !== null ? p.oaaScore.toFixed(1) : "N/A",
  ]);

  (doc as unknown as DocWithAutoTable).autoTable({
    startY: finalY1 + 14,
    head: [["Rank", "Student Name", "Average Score", "Assigned Grade", "Composite OAA Score"]],
    body: topRows,
    theme: "striped",
    headStyles: { fillColor: primaryColor, fontStyle: "bold", fontSize: 8.5 },
    bodyStyles: { textColor: darkSlate, fontSize: 8 },
    columnStyles: {
      4: { fontStyle: "bold", halign: "center" },
    },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    margin: { left: 15, right: 15 },
  });

  // Section 4: At-risk students table
  const finalY2 = (doc as unknown as DocWithAutoTable).lastAutoTable.finalY;

  // Check if we need to add a new page
  if (finalY2 + 45 > 280) {
    doc.addPage();
    drawPageDecorations(2);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
    doc.text("At-Risk Student Alerts (AI prediction & Behavioral flags)", 15, 20);
    
    const riskRows = data.atRiskStudents.map((r) => [
      r.name,
      `${r.avgMarks.toFixed(1)}%`,
      `${r.attendance.toFixed(1)}%`,
      `${(r.riskScore * 100).toFixed(0)}%`,
      `${r.redDotCount} Red Dots`,
    ]);

    (doc as unknown as DocWithAutoTable).autoTable({
      startY: 24,
      head: [["Student Name", "Average Marks", "Attendance Rate", "AI Prediction Risk", "Behavioral Infractions"]],
      body: riskRows,
      theme: "striped",
      headStyles: { fillColor: [225, 29, 72], fontStyle: "bold", fontSize: 8.5 }, // red-600 for warnings
      bodyStyles: { textColor: darkSlate, fontSize: 8 },
      alternateRowStyles: { fillColor: [255, 241, 242] },
      margin: { left: 15, right: 15 },
    });
  } else {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
    doc.text("At-Risk Student Alerts (AI prediction & Behavioral flags)", 15, finalY2 + 10);

    const riskRows = data.atRiskStudents.map((r) => [
      r.name,
      `${r.avgMarks.toFixed(1)}%`,
      `${r.attendance.toFixed(1)}%`,
      `${(r.riskScore * 100).toFixed(0)}%`,
      `${r.redDotCount} Red Dots`,
    ]);

    (doc as unknown as DocWithAutoTable).autoTable({
      startY: finalY2 + 14,
      head: [["Student Name", "Average Marks", "Attendance Rate", "AI Prediction Risk", "Behavioral Infractions"]],
      body: riskRows,
      theme: "striped",
      headStyles: { fillColor: [225, 29, 72], fontStyle: "bold", fontSize: 8.5 }, // red accent
      bodyStyles: { textColor: darkSlate, fontSize: 8 },
      alternateRowStyles: { fillColor: [255, 241, 242] }, // light red
      margin: { left: 15, right: 15 },
    });
  }

  // Trigger browser download
  doc.save(`class_report_${data.className.toLowerCase().replace(/\s+/g, "_")}.pdf`);
}
