import { jsPDF } from "jspdf";
import "jspdf-autotable";

export interface StudentReport {
  studentName: string;
  className: string;
  sectionName: string;
  schoolName: string;
  gender: string;
  summary: {
    avgMarks: number;
    attendanceRate: number;
    rank: number;
    grade: string;
    oaaScore: number | null;
    percentileRank: number | null;
    academicScore: number | null;
    skillsScore: number | null;
    projectScore: number | null;
    behaviorScore: number | null;
  };
  subjects: {
    subject: string;
    exam1: number | null;
    exam2: number | null;
    final: number | null;
    avg: number;
    grade: string;
  }[];
  attendance: {
    present: number;
    absent: number;
    late: number;
    percentage: number;
    streak: number;
  };
  aiInsights: {
    riskLevel: "High" | "Medium" | "Low";
    riskScore: number;
    suggestions: string[];
  } | null;
}

export function generateStudentPDF(data: StudentReport): void {
  const doc = new jsPDF();
  const primaryColor = [79, 70, 229]; // #4F46E5 (Indigo)
  const darkSlate = [30, 41, 59]; // #1E293B (Slate-800)
  const lightSlate = [100, 116, 139]; // #64748B (Slate-500)
  const borderSlate = [226, 232, 240]; // #E2E8F0 (Slate-200)

  const drawPageDecorations = (pageNum: number) => {
    // Top border accent
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, 210, 4, "F");

    // Header branding
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text("OAA.ai", 15, 12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
    doc.text("Overall Academic Analysis Platform", 29, 12);

    // Footer
    doc.setFontSize(8);
    doc.text(`Generated by OAA.ai Student Analytics  |  Page ${pageNum}`, 15, 287);
    doc.text(new Date().toLocaleDateString(), 165, 287);
  };

  drawPageDecorations(1);

  // Profile Header Card (with avatar placeholder)
  doc.setFillColor(248, 250, 252); // bg-slate-50
  doc.rect(15, 18, 180, 36, "F");
  doc.setDrawColor(borderSlate[0], borderSlate[1], borderSlate[2]);
  doc.rect(15, 18, 180, 36, "S");

  // Avatar box
  doc.setFillColor(224, 231, 255); // bg-indigo-100
  doc.rect(21, 22, 28, 28, "F");
  doc.setDrawColor(199, 210, 254);
  doc.rect(21, 22, 28, 28, "S");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  
  // Draw initials in photo box
  const initials = data.studentName.split(" ").map(n => n[0]).join("").slice(0, 2).toUpperCase();
  doc.text(initials, 31, 39);

  // Student Details text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.text(data.studentName, 56, 27);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
  doc.text(`SCHOOL: ${data.schoolName.toUpperCase()}`, 56, 33);
  doc.text(`CLASS / SECTION: ${data.className} - ${data.sectionName}`, 56, 38);
  doc.text(`GENDER: ${data.gender.toUpperCase()}`, 56, 43);
  doc.text(`REPORT RUN DATE: ${new Date().toLocaleDateString()}`, 56, 48);

  // Section 1: OAA COMPOSITE SCORE DASHBOARD
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.text("Overall Academic Analysis (OAA) Dashboard", 15, 61);

  // Shaded OAA container box
  doc.setFillColor(243, 244, 246); // bg-gray-100
  doc.rect(15, 65, 180, 42, "F");
  doc.setDrawColor(209, 213, 219); // border-gray-300
  doc.rect(15, 65, 180, 42, "S");

  // OAA Score Badge (Big number)
  const oaaValue = data.summary.oaaScore !== null ? data.summary.oaaScore : 0;
  doc.setFillColor(79, 70, 229); // indigo-600
  doc.rect(20, 71, 38, 30, "F");
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.text(oaaValue.toFixed(1), 25, 89);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.text("COMPOSITE SCORE", 23, 97);

  // Percentile details
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.text(`Percentile Rank: ${data.summary.percentileRank !== null ? `${data.summary.percentileRank.toFixed(1)}%` : "N/A"}`, 65, 75);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
  doc.text(`Academic Class Rank: #${data.summary.rank}`, 65, 80);

  // Small separator
  doc.setDrawColor(229, 231, 235);
  doc.line(65, 83, 185, 83);

  // OAA Pillars breakdown metrics (4 columns inside container)
  const pillarY = 88;
  const pillarGap = 32;
  const pillarLabels = [
    { name: "Academics", score: data.summary.academicScore, max: 40, color: [79, 70, 229] },
    { name: "Skills", score: data.summary.skillsScore, max: 30, color: [16, 185, 129] },
    { name: "Projects", score: data.summary.projectScore, max: 20, color: [245, 158, 11] },
    { name: "Behavior", score: data.summary.behaviorScore, max: 10, color: [239, 68, 68] }
  ];

  pillarLabels.forEach((p, idx) => {
    const x = 65 + idx * pillarGap;
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
    doc.text(p.name, x, pillarY);

    const valStr = p.score !== null ? `${p.score.toFixed(1)}/${p.max}` : `0/${p.max}`;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
    doc.text(valStr, x, pillarY + 4.5);

    // Draw tiny progress bar
    doc.setFillColor(229, 231, 235);
    doc.rect(x, pillarY + 6.5, 25, 2, "F");
    const fillPercent = p.score !== null ? p.score / p.max : 0;
    doc.setFillColor(p.color[0], p.color[1], p.color[2]);
    doc.rect(x, pillarY + 6.5, Math.max(0, 25 * fillPercent), 2, "F");
  });

  // Section 2: Subject Marks Table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.text("Subject-wise Academic Performance", 15, 114);

  const subjectRows = data.subjects.map((s) => [
    s.subject,
    s.exam1 !== null ? `${s.exam1.toFixed(1)}%` : "-",
    s.exam2 !== null ? `${s.exam2.toFixed(1)}%` : "-",
    s.final !== null ? `${s.final.toFixed(1)}%` : "-",
    `${s.avg.toFixed(1)}%`,
    s.grade,
  ]);

  type DocWithAutoTable = jsPDF & { 
    autoTable: (opt: object) => void;
    lastAutoTable: { finalY: number };
  };

  (doc as unknown as DocWithAutoTable).autoTable({
    startY: 119,
    head: [["Subject Title", "Unit Tests / Classwork", "Midterm Examination", "Final Examination", "Subject Cumulative", "Grade"]],
    body: subjectRows,
    theme: "grid",
    headStyles: { fillColor: primaryColor, fontStyle: "bold", fontSize: 8.5 },
    bodyStyles: { textColor: darkSlate, fontSize: 8 },
    columnStyles: {
      5: { fontStyle: "bold", halign: "center" },
    },
    willDrawCell: (cellData: unknown) => {
      const cData = cellData as {
        column: { index: number };
        section: string;
        cell: { raw: unknown; styles: { fillColor: number[] | number; textColor: number[] | number } };
      };
      if (cData.column.index === 5 && cData.section === "body") {
        const val = cData.cell.raw;
        if (typeof val === "string") {
          if (val.startsWith("A")) {
            cData.cell.styles.fillColor = [209, 250, 229]; // emerald-100
            cData.cell.styles.textColor = [6, 95, 70]; // emerald-800
          } else if (val.startsWith("B") || val.startsWith("C")) {
            cData.cell.styles.fillColor = [254, 243, 199]; // amber-100
            cData.cell.styles.textColor = [146, 64, 14]; // amber-800
          } else if (val.startsWith("F") || val === "D") {
            cData.cell.styles.fillColor = [254, 226, 226]; // rose-100
            cData.cell.styles.textColor = [153, 27, 27]; // rose-800
          }
        }
      }
    },
    margin: { left: 15, right: 15 },
  });

  // Section 3: Attendance Summary
  const tableY = (doc as unknown as DocWithAutoTable).lastAutoTable.finalY;
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.text("Attendance & Class Engagement Log", 15, tableY + 10);

  const attRows = [[
    String(data.attendance.present),
    String(data.attendance.absent),
    String(data.attendance.late),
    `${(data.attendance.percentage * 100).toFixed(1)}%`,
    `${data.attendance.streak} days`,
  ]];

  (doc as unknown as DocWithAutoTable).autoTable({
    startY: tableY + 14,
    head: [["Present Days", "Absent Days", "Late Arrivals", "Attendance Rate", "Max Absence Streak"]],
    body: attRows,
    theme: "striped",
    headStyles: { fillColor: [71, 85, 105], fontStyle: "bold", fontSize: 8.5 }, // slate-600
    bodyStyles: { textColor: darkSlate, halign: "center", fontSize: 8 },
    margin: { left: 15, right: 15 },
  });

  // Section 4: AI Insights Box
  const attY = (doc as unknown as DocWithAutoTable).lastAutoTable.finalY;
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.text("OAA.ai Predictive Intelligence Insights", 15, attY + 10);

  if (data.aiInsights) {
    const riskColor = data.aiInsights.riskLevel === "High"
      ? [225, 29, 72] // rose-600
      : data.aiInsights.riskLevel === "Medium"
      ? [245, 158, 11] // amber-500
      : [16, 185, 129]; // emerald-500

    // Box container
    doc.setFillColor(250, 245, 255); // bg-purple-50
    doc.rect(15, attY + 14, 180, 32, "F");
    doc.setDrawColor(233, 213, 255); // border-purple-200
    doc.rect(15, attY + 14, 180, 32, "S");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
    doc.text("CLASSIFIED RISK STATE:", 20, attY + 21);
    
    doc.setFont("helvetica", "bold");
    doc.setTextColor(riskColor[0], riskColor[1], riskColor[2]);
    doc.text(`${data.aiInsights.riskLevel.toUpperCase()} RISK`, 65, attY + 21);

    doc.setFont("helvetica", "bold");
    doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
    doc.text(`AI Risk Score: ${(data.aiInsights.riskScore * 100).toFixed(0)}%`, 130, attY + 21);

    // Bullet points for suggestions
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
    let textY = attY + 27;
    const suggestions = data.aiInsights.suggestions.slice(0, 2);
    suggestions.forEach((s) => {
      doc.text(`• ${s}`, 20, textY);
      textY += 4.5;
    });
  } else {
    // Normal fallback
    doc.setFillColor(248, 250, 252);
    doc.rect(15, attY + 14, 180, 20, "F");
    doc.setDrawColor(borderSlate[0], borderSlate[1], borderSlate[2]);
    doc.rect(15, attY + 14, 180, 20, "S");
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8.5);
    doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
    doc.text("No active AI predictions generated. Recalculate predictions from the AI dashboard.", 22, attY + 26);
  }

  // Section 5: Teacher Remarks Placeholder
  const aiBoxY = data.aiInsights ? attY + 46 : attY + 34;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(darkSlate[0], darkSlate[1], darkSlate[2]);
  doc.text("Official Remarks & Feedback", 15, aiBoxY + 8);

  // Remarks lines
  doc.setDrawColor(borderSlate[0], borderSlate[1], borderSlate[2]);
  doc.line(15, aiBoxY + 14, 195, aiBoxY + 14);
  doc.line(15, aiBoxY + 21, 195, aiBoxY + 21);
  doc.line(15, aiBoxY + 28, 195, aiBoxY + 28);

  // Signatures
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(lightSlate[0], lightSlate[1], lightSlate[2]);
  doc.text("_______________________", 20, aiBoxY + 44);
  doc.text("Teacher Signature", 30, aiBoxY + 49);

  doc.text("_______________________", 140, aiBoxY + 44);
  doc.text("Principal Signature", 150, aiBoxY + 49);

  // Trigger browser download
  doc.save(`student_report_${data.studentName.toLowerCase().replace(/\s+/g, "_")}.pdf`);
}
